## INPUTS

# `se_peak_cell`
# SummarizedExperiment
# Contains Peak-Cell matrix
se_peak_cell:
  h5: "/work/DevM_analysis/06.phenotypes/01.archr_export/se/se_peak10k_cell10k_48FL_assays.h5"
  rds: "/work/DevM_analysis/06.phenotypes/01.archr_export/se/se_peak10k_cell10k_48FL_se.rds"

# `sample_metadata`
# CSV file
# Annotations for samples
sample_metadata: "/work/DevM_analysis/utils/sam_info.DevM.22.10.24.csv"

# `tmp_dir`
tmp_dir: "/work/aaa/tmp"

# `trait_sets`
# dictionary of trait sets
# each set must contain:
#   - `base_path` - path to find traits
#   - `traits` - dictionary of {trait_name: trait_file} pairs.
# we recommend defining traitsets modularly in separate config files
# see config/config-gwas.yaml for the "default" trait set

## PARAMETERS

# `n_background`
# integer [1, ...)
# chromVAR parameter
# defines number of background peak samples to generate
# SCAVENGE and Marderstein, 2024 use 200
n_background: 200

# `n_neighbors`
# integer [1, ...)
# SCAVENGE parameter
# defines number of neighbors to use in the kNN graph
# SCAVENGE and Marderstein, 2024 use 30
n_neighbors: 30

# `n_perms`
# integer [1, ...)
# SCAVENGE parameter
# defines number of permutations to use in estimating null distribution of network propagation scores
# SCAVENGE and Marderstein, 2024 use 1000
n_perms: 1000

# `n_subsample_per_sample`
# integer [1, ...)
# pipeline parameter (optional)
# if using subsampling, sets max number of subsampled cells per sample
n_subsample_per_sample: 300

# `key_sample`
# string
# pipeline parameter (optional)
# if using sample-based subsampling, defines the sample key (column) to subsampling within
key_sample: "sampleID"

# `frac_seed_max`
# double (0,1]
# SCAVENGE parameter
# defines upper limit on fraction of cells that can be seeds
# SCAVENGE and Marderstein, 2024 use 0.05
frac_seed_max: 0.05

# `frac_scale_cut`
# double (0,1]
# SCAVENGE parameter
# defines fraction of highest ranked cells that should be used to compute scaling coefficient
# SCAVENGE and Marderstein, 2024 use 0.01
frac_scale_cut: 0.01

# `gamma_rw`
# double [0,1)
# SCAVENGE parameter
# defines restart probability for PageRank random walk algorithm
# SCAVENGE and Marderstein, 2024 use 0.05
gamma_rw: 0.05

# `q_ceiling`
# double [0,1)
# SCAVENGE parameter
# defines quantile that will be used as the ceiling of TRS
# SCAVENGE and Marderstein, 2024 use 0.95
q_ceiling: 0.95

# `pvalue_sig_cell`
# double (0,1]
# SCAVENGE parameter
# defines p-value threshold for significant network propagation scores
# SCAVENGE and Marderstein, 2024 use 0.05
pvalue_sig_cell: 0.05

# `seed_rng`
# integer [0, ...)
# pipeline parameter
# defines the seed used to initialize the pseudorandom state
seed_rng: 20241104
